---
- name: install postgresql
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2
  become: yes

- name: configure postgresql
  copy:
    src: postgresql.conf
    dest: /etc/postgresql/9.5/main
    group: postgres
    owner: postgres
  become: yes
  notify:
    - reload postgres

- name: configure postgresql hba
  copy:
    src: pg_hba.conf
    dest: /etc/postgresql/9.5/main
    group: postgres
    owner: postgres
  become: yes
  notify:
    - reload postgres

- name: create postgresql db
  postgresql_db:
    name: "{{ db.name }}"
    state: present
  become: yes
  become_user: postgres

- name: create postgresql user
  postgresql_user:
    db: "{{ db.name }}"
    name: "{{ db.user }}"
    password: "{{ db.pass }}"
    priv: ALL
    role_attr_flags: NOSUPERUSER,NOCREATEDB
    state: present
  become: yes
  become_user: postgres

- name: restrict db access to postgresql user
  postgresql_privs:
    db: "{{ db.name }}"
    priv: ALL
    role: PUBLIC
    type: database
    state: absent
  become: yes
  become_user: postgres
